apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  components:
    - name: my-app
      type: webservice
      properties:
        image: yilitest.azurecr.io/app/test-fog:master-c38379ba-1634977126 # {"$imagepolicy": "default:image-gitops"}
